# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/billie/setup-makefiles.sh

AB_OTA_PARTITIONS += \
    abl \
    aop \
    bluetooth \
    devcfg \
    dsp \
    featenabler \
    hyp \
    imagefv \
    keymaster \
    modem \
    qupfw \
    storsec \
    tz \
    uefisecapp \
    xbl \
    xbl_config
